Fix: handle git fetch error
Fix an unhandled exception when `git fetch` fails.
When this occurs, it is okay to return no new commits;
the main thread will simply retry on the next iteration.

Traceback (most recent call last):
  File "combotcha.py", line 170, in <module>
    with open(sys.argv[1]) as cfg_file:
  File "combotcha.py", line 35, in get_new_commits

  File "/home/jgalar/combotcha/lib/python3.6/site-packages/git/remote.py", line 789, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/home/jgalar/combotcha/lib/python3.6/site-packages/git/remote.py", line 675, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/home/jgalar/combotcha/lib/python3.6/site-packages/git/cmd.py", line 415, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v origin
  stderr: 'fatal: unable to access 'https://github.com/efficios/barectf.git/': Could not resolve host: github.com'

Signed-off-by: Jérémie Galarneau <jeremie.galarneau@gmail.com>